### PR TITLE
composer.json - php version updated

### PR DESCRIPTION
**Pull request by pmiroslawski**
I can't see any tests but everything should be fine ;)

### CODE REVIEW

**Comment by tomas-kulhanek** [comment]
@pmiroslawski 
Why you are change package name?

**Comment by pmiroslawski** [comment]
Oh sorry, wanted to check if everything is fine and didn't know it will be a part of this PR.

**Comment by tomas-kulhanek** [comment]
I don`t have any tests, because i dont have any time. But maybe in the future :) 
@pmiroslawski thanks

**Comment by pmiroslawski** [comment]
That's ok :) 

thanks

**Comment by tomas-kulhanek** [comment]
@pmiroslawski release v1.0.6 for your changes is created

**Pull request merged**
